JENKINS BUILD FAILED D:\Development\sdk\tools\ant\build.xml:720: The following error occurred while executing this line: D:\Development\sdk\tools\ant\build.xml:734: Compile failed; see the compiler error output for details.
Total time: 44 seconds
Build step 'Invoke Ant' marked build as failure
[FINDBUGS] Skipping publisher since build result is FAILURE
[PMD] Skipping publisher since build result is FAILURE
[DRY] Skipping publisher since build result is FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level C:\Jenkins_Slave\workspace\DigitalCare_Android_Debug to /var/lib/jenkins/jobs/DigitalCare_Android_Debug/builds/343/htmlreports/Code-Complexity-Report
[android-lint] Skipping publisher since build result is FAILURE
Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
hudson.AbortException: Test reports were found but none of them are new. Did tests run?
For example, C:\Jenkins_Slave\workspace\DigitalCare_Android_Debug\DigitalCareTestFramework\reports\junit-report.xml is 15 min old